import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const settings = readFileSync(resolve(__dirname, '../../src/pages/Settings.tsx'), 'utf8')
const routes = readFileSync(resolve(__dirname, '../../../src/routes/project.routes.ts'), 'utf8')

assert.match(settings, /Настройки проекта/)
assert.match(settings, /Подключение MCP/)
assert.match(settings, /Штаб планирования/)
assert.match(settings, /Контент-агент/)
assert.match(settings, /MCP_PLANNER_AUTH_TOKEN/)
assert.match(settings, /MCP_WRITER_AUTH_TOKEN/)
assert.match(settings, /MCP_EDITOR_AUTH_TOKEN/)
assert.match(settings, /MCP_PUBLISHER_AUTH_TOKEN/)
assert.match(settings, /MCP_GROWTH_ANALYST_AUTH_TOKEN/)
assert.match(settings, /Развернуть 7 ролей/)
assert.match(settings, /workspace-access/)
assert.match(settings, /Отозвать весь пакет/)
assert.match(settings, /Ротировать 7 ролей/)
assert.match(settings, /mcp\/status/)
assert.match(settings, /MCP работает/)
assert.match(settings, /ba_get_agent_workspace_manifest/)
assert.match(settings, /ba_get_agent_workspace_updates/)
assert.match(settings, /ba_get_agent_chat_bootstrap/)
assert.match(settings, /Проверить/)
assert.match(settings, /Только подготовка/)
assert.match(settings, /Публикация после одобрения/)
assert.match(settings, /Автопубликация/)
assert.match(settings, /Как подключить VK/)
assert.match(settings, /How to connect VK/)
assert.match(settings, /Управление → Работа с API → Ключи доступа/)
assert.match(settings, /Planner never reveals a saved token again/)
assert.equal((settings.match(/<VkConnectionGuide/g) || []).length, 2)
assert.match(settings, /Как подключить Telegram/)
assert.match(settings, /How to connect Telegram/)
assert.match(settings, /TELEGRAM_BOT_TOKEN/)
assert.equal((settings.match(/<TelegramConnectionGuide/g) || []).length, 2)
assert.match(settings, /Как подключить Дзен/)
assert.match(settings, /How to connect Zen/)
assert.match(settings, /Проверить подключение к Дзену/)
assert.equal((settings.match(/<DzenConnectionGuide/g) || []).length, 2)
assert.match(settings, /workflow_mode/)
assert.match(settings, /className="channel-table"/)
assert.match(settings, /channel-table__status--attention/)
assert.match(settings, /Идентификатор/)
assert.match(settings, /Connection required/)
assert.match(settings, /currentMembership\?\.role === 'owner'/)
assert.match(settings, /fieldset disabled={!isOwner}/)
assert.doesNotMatch(settings, /<h1 className="mb-3">Project Settings/)

const settingsRoute = routes.slice(routes.indexOf("fastify.post('/api/projects/:id/settings'"), routes.indexOf('// Get project details'))
assert.match(settingsRoute, /hasProjectAccess\(user\.id, projectId, 'owner'\)/)

assert.match(routes, /fastify\.post\('\/api\/projects\/:id\/channels'/)
assert.match(routes, /fastify\.put\('\/api\/projects\/:id\/channels\/:channelId'/)
assert.match(routes, /fastify\.delete\('\/api\/projects\/:id\/channels\/:channelId'/)
assert.match(routes, /fastify\.post\('\/api\/projects\/:id\/mcp\/workspace-access'/)
