import { decryptChannelSecret, encryptChannelSecret } from './channel_secrets';

const DZEN_TYPES = new Set(['zen', 'zen_article', 'dzen']);

/**
 * Sanitize channel configuration before returning it to the client by masking secrets.
 */
export function sanitizeChannelConfig(type: string, config: any): any {
    if (!config || typeof config !== 'object') return config;
    const sanitized = { ...config };
    if (sanitized.raw_account && typeof sanitized.raw_account === 'object') {
        sanitized.raw_account = sanitizeChannelConfig(type, sanitized.raw_account);
    }
    
    // Mask sensitive fields
    if (sanitized.api_key) sanitized.api_key = '******';
    if (sanitized.publish_access_token) sanitized.publish_access_token = '******';
    if (sanitized.stats_access_token) sanitized.stats_access_token = '******';
    if (sanitized.access_token) sanitized.access_token = '******';
    if (sanitized.cookies) sanitized.cookies = '******';
    if (sanitized.cookies_encrypted) {
        sanitized.cookies = '******';
        delete sanitized.cookies_encrypted;
    }
    if (sanitized.application_secret_key) sanitized.application_secret_key = '******';
    
    return sanitized;
}

/**
 * Merge incoming configuration with existing channel configuration to preserve masked secrets.
 */
export function mergeChannelConfig(incomingConfig: any, existingConfig: any): any {
    if (!existingConfig || typeof existingConfig !== 'object') return incomingConfig;
    const merged = { ...incomingConfig };
    
    const secretKeys = ['api_key', 'publish_access_token', 'stats_access_token', 'access_token', 'cookies', 'application_secret_key'];
    for (const key of secretKeys) {
        if (merged[key] === '******' && existingConfig[key]) {
            merged[key] = existingConfig[key];
        }
    }

    if (merged.cookies === '******' && existingConfig.cookies_encrypted) {
        delete merged.cookies;
        merged.cookies_encrypted = existingConfig.cookies_encrypted;
    }
    
    return merged;
}

export function prepareChannelConfigForStorage(type: string, config: any): any {
    const prepared = { ...(config || {}) };
    if (!DZEN_TYPES.has(type)) return prepared;

    if (prepared.raw_account && typeof prepared.raw_account === 'object') {
        prepared.raw_account = prepareChannelConfigForStorage(type, prepared.raw_account);
    }

    const cookies = typeof prepared.cookies === 'string' ? prepared.cookies.trim() : '';
    if (cookies && cookies !== '******') {
        prepared.cookies_encrypted = encryptChannelSecret(cookies);
    }
    delete prepared.cookies;
    return prepared;
}

export function resolveChannelConfigSecrets(type: string, config: any): any {
    const resolved = { ...(config || {}) };
    if (!DZEN_TYPES.has(type)) return resolved;

    if (resolved.raw_account && typeof resolved.raw_account === 'object') {
        resolved.raw_account = resolveChannelConfigSecrets(type, resolved.raw_account);
        if (!resolved.cookies && resolved.raw_account.cookies) {
            resolved.cookies = resolved.raw_account.cookies;
        }
    }

    if (!resolved.cookies && typeof resolved.cookies_encrypted === 'string') {
        resolved.cookies = decryptChannelSecret(resolved.cookies_encrypted);
    }
    delete resolved.cookies_encrypted;
    return resolved;
}

/**
 * Clean up, format, and append hashtags to a post text, ensuring no duplicates or double hashes.
 */
export function cleanAndFormatHashtags(text: string, tags: string[], category?: string): string {
    let fullText = text || '';
    
    // Clean up any existing double hashtags generated by LLM (e.g. ##tag -> #tag)
    fullText = fullText.replace(/#+#/g, '#').replace(/##+/g, '#');

    if (tags && tags.length > 0) {
        const hashtagsToAppend = tags
            .map(t => `#${t.replace(/\s+/g, '').replace(/^#+/, '')}`)
            .filter(tag => {
                // Prevent duplicate addition of tags if already present in body text
                const escapedTag = tag.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
                const regex = new RegExp(escapedTag + '\\b', 'i');
                return !regex.test(fullText);
            });

        if (hashtagsToAppend.length > 0) {
            fullText = fullText.trim() + '\n\n' + hashtagsToAppend.join(' ');
        }
    } else if (category) {
        const catTag = `#${category.replace(/\s+/g, '').replace(/^#+/, '')}`;
        const escapedCatTag = catTag.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
        const regex = new RegExp(escapedCatTag + '\\b', 'i');
        if (!regex.test(fullText)) {
            fullText = fullText.trim() + '\n\n' + catTag;
        }
    }

    // Final sweep to remove any accidental double hashtag artifacts
    fullText = fullText.replace(/#+#/g, '#').replace(/##+/g, '#');
    return fullText;
}
